remote_theme: BDHU/minimalist
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

url: https://giminkang.github.io
repository: GiminKang/GiminKang.github.io
# color-scheme: auto
color-scheme: light

title: Gimin Kang
description: "B.S. student<br> Industrial and System Engineering, KAIST"
logo: "./assets/DA Form.jpg"

search: true
search_full_content: true

sidebar:
  - name: CV
    icon: <i class="fas fa-fw fa-file"></i>
    link: "https://giminkang.github.io/assets/Resume.pdf"
  - name: Email
    icon: <i class="fas fa-fw fa-envelope-square"></i>
    link: "mailto:kgm4752@kaist.ac.kr"
  - name: GitHub
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: "https://github.com/GiminKang"
  - name: Google scholar
    icon: <i class="fab fa-fw fa-google-scholar"></i>
    link: "https://scholar.google.com/citations?user=kyabkaMAAAAJ&hl=ko"